### PR TITLE
Update BelongsToObserver

### PR DESCRIPTION
**Pull request by mahentoo**
In cases where it is necessary to create (parent) during editing (model).

### CODE REVIEW

**Comment by brandonferens** [comment]
Thank you @mahentoo for this PR. We are looking over this internally and will let you know if we have any questions are comments!

**Comment by brandonferens** [comment]
@mahentoo We'd like a couple formatting/reorganization changes. Could you please update the code to look like this:
```php
$parentModel = $model->{$attribute}()->first();

if (empty($parentModel)) {
    return $this->creating($model, $attribute, $value);
}

if (count($value)) {
    $parentModel->update($value[0]);
}
```

Once that is done, we will merge it in!

**Comment by mahentoo** [comment]
@brandonferens 
Done in #29

**Comment by brandonferens** [comment]
Thanks @mahentoo!

**Pull request closed without merging**
