### PR TITLE
Use of panel fix (issue #10)

### LINKED ISSUE #10: Does not work inside Panels (or Tabs)
This looks amazing but having problems when using it inside Nova's Panel (or tabs, using eminiarts/nova-tabs). There are no error or anything on saving, but it doesn't save any changes or new values. My code is pretty simple:

```php
// Product resource
public function fields(Request $request)
{
	return [
		new Panel('Product', [
			ID::make()->sortable(),
			Text::make('Title', 'title'),
		]),
		new Panel('Discounts', [
			HasMany::make('Discounts', 'discounts', ProductDiscount::class)->inline(),
		])
	];
}

// ProductDiscount resource
public function fields(Request $request)
{
	return [
		ID::make(),
		BelongsTo::make ('Product', 'product', Product::class),
		Number::make('Amount', 'amount'),
		Number::make('Discount', 'price_discount'),
	];
}
```

Any ideas?

### PR DESCRIPTION
**Pull request by timvanuum**
This fixes the use of Panels and custom classes that extends the Panel. #10 

Example:
```
public function fields(Request $request)
    {
        return [
            ResourceNavigationTab::make('Algemeen', [
                ID::make()->hideFromIndex()->sortable(),
                Text::make('Naam', 'name')->sortable()->rules('required'),
                BelongsTo::make('domain'),
                Froala::make('Inhoud', 'content')->sortable()->withFiles('public'),
                Boolean::make('Actief', 'active'),
            ]),
            ResourceNavigationTab::make('Seo', [
                MorphOne::make('Seo', 'seo', \App\Nova\Seo::class )
                    ->inline()
                    ->hideFromIndex()
            ])
        ];
    }
```

### CODE REVIEW

**Comment by Stiropor** [comment]
This works just perfectly! Just tested updating and creating. Thank you so very much, @timvanuum !

**Comment by Stiropor** [comment]
@timvanuum This fix doesn't work when field is not inside Tab or Panel.

**Comment by brandonferens** [comment]
@timvanuum Thanks so much for the PR. Would you mind looking at your code changes and see if you can address @Stiropor 's concern with not working outside of Tab or Panel?

If I get a chance sometime soon I will try to get to it as well.

**Comment by brandonferens** [comment]
@timvanuum I would like to make a tweak to your PR. Please wrap the `$value` at then end of the ternary in `flatMap()` in array brackets like this:
```php
->flatMap(function ($value) {
    return $value instanceof Panel
        ? $value->data
        : [$value];
})
```
After this, I can merge in this PR as it works both inside of and outside of Panels.

**Pull request merged**
