### PR TITLE
Nova 4 Upgrade

### PR DESCRIPTION
**Pull request by wilkerwma**
This PR will add Nova 4 Support since the new nova inline relationship features do not cover all scenarios we need and are provided by this package.

Tasks:
- [x] Update `composer.json` to use Nova4 and PHP8
- [x] Update `package.json` with the newest js libs
- [x] Add/Update js files to Nova4 Structure (mix.js/webpack.mix.js)
- [x] Make `->inline()` option work 
- [x] Make `DetailsView` component work
    - [x] Update `DetailField.vue` logic and style
    - [x] Update `RelationshipDetailItem` logic and style
- [x] Make `EditView` component work
    - [x] Update `FormField.vue` logic and style
        - [x] Make component draggable 
    - [x] Update `RelationshipFormItem` logic and style
        - [x] Fix update request and filling logic
- [x] Fix tests

### CODE REVIEW

**Comment by wilkerwma** [comment]
Still struggling to make the draggable function work. 
The update ability is broken, and all the relationships are erased after an update attempt.

**Comment by wilkerwma** [comment]
Some screen previews:
### Form
Screenshot 2023-02-01 at 19 09 53

### Details
Screenshot 2023-02-01 at 19 07 58

**Comment by jmverges** [comment]
👋 @wilkerwma is it working now? Many thanks!

**Comment by luisdalmolin** [comment]
@jmverges We should be close to merging and releasing this 🙏

**Review by luisdalmolin — APPROVED** [review]

**Pull request merged**
